function [ bbox ] = getBBoxFromLocators(box_locators)
% this function takes all the box locators and create
% bouding box for each interest area
    % left eye box
    left_eye_box = [box_locators.left_eye.left - 10, box_locators.left_eye.top - 10, ...
        box_locators.left_eye.right - box_locators.left_eye.left + 20, ...
        box_locators.left_eye.bottom - box_locators.left_eye.top + 20];
    % right eye box
    right_eye_box = [box_locators.right_eye.left - 10, box_locators.right_eye.top - 10, ...
        box_locators.right_eye.right - box_locators.right_eye.left + 20, ...
        box_locators.right_eye.bottom - box_locators.right_eye.top + 20];
    % left eye bottom box
    left_eye_bottom_box = [box_locators.left_eye_bag.left - 10, box_locators.left_eye_bag.top - 10, ...
        box_locators.left_eye_bag.right - box_locators.left_eye_bag.left + 20, ...
        box_locators.left_eye_bag.bottom - box_locators.left_eye_bag.top + 20];
    % right eye bottom box
    right_eye_bottom_box = [box_locators.right_eye_bag.left - 10, box_locators.right_eye_bag.top - 10, ...
        box_locators.right_eye_bag.right - box_locators.right_eye_bag.left + 20, ...
        box_locators.right_eye_bag.bottom - box_locators.right_eye_bag.top + 20];
    % check box
    check_box = [box_locators.pale_skin.left, box_locators.pale_skin.top, ...
        box_locators.pale_skin.right - box_locators.pale_skin.left, ...
        box_locators.pale_skin.bottom - box_locators.pale_skin.top];
    % mouse box
    mouse_box = [box_locators.mouth.left - 10, box_locators.mouth.top - 10, ...
        box_locators.mouth.right - box_locators.mouth.left + 20, ...
        box_locators.mouth.bottom - box_locators.mouth.top + 20];
    
    bbox = {left_eye_box, right_eye_box, left_eye_bottom_box, right_eye_bottom_box, ...
            check_box, mouse_box};
end
