# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Panda' do
    
    # Database
    pod 'AVOSCloud'       
    # UI components
    pod 'NVActivityIndicatorView'
    pod 'JTSImageViewController'
    pod 'JTMaterialSwitch'
    pod 'StepSlider'
    pod 'SVWebViewController'

end

target 'PandaTests' do

end

target 'PandaUITests' do

end

