# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TrainingDataCluster' do

end

target 'TrainingDataClusterTests' do

end

target 'TrainingDataClusterUITests' do

end

